server:
  port: 8081
  servlet:
    context-path: /api
jwt:
  secret: 8w475hg8w47hg457h98754hg8w3127hwo358hg
  lifetime: 3600000
spring:
  servlet:
    multipart:
      max-file-size: 32MB
      max-request-size: 32MB
  datasource:
    url: jdbc:postgresql://localhost:5432/map
    username:
    password:
  flyway:
    locations: classpath:/db/migration
    url: jdbc:postgresql://localhost:5432/map
    schemas: public
    user:
    password:
    connect-retries: 60
    validate-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties.mail.smtp:
      auth: true
      starttls.enable: true
